[project]
name = "streamlit_app"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.13.2",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "python-multipart>=0.0.20",
    "sqlmodel>=0.0.27",
    "streamlit>=1.51.0",
    "typing>=3.10.0.0",
]
